export const IranProvinces: {name: string, code: number}[] = [
    {name:"آذربایجان شرقی", code: 10},
    {name:"آذربایجان غربی", code: 11},
    {name:"اصفهان", code: 12},
    {name:"خراسان رضوی", code: 13},
    {name:"خوزستان", code: 14},
    {name:"فارس", code: 15},
    {name:"کرمان", code: 16},
    {name:"کرمانشاه", code: 17},
    {name:"گیلان", code: 18},
    {name:"مازندران", code: 19},
    {name:"مرکزی", code: 20},
    {name:"سیستان و بلوچستان", code: 21},
    {name:"کردستان", code: 22},
    {name:"هرمزگان", code: 23},
    {name:"بوشهر", code: 24},
    {name:"چهارمحال و بختیاری", code: 25},
    {name:"زنجان", code: 26},
    {name:"لرستان", code: 27},
    {name:"همدان", code: 28},
    {name:"یزد", code: 29},
    {name:"ایلام", code: 30},
    {name:"سمنان", code: 31},
    {name:"کهگیلویه و بویراحمد", code: 32},
    {name:"تهران", code: 33},
    {name:"اردبیل", code: 34},
    {name:"قم", code: 35},
    {name:"قزوین", code: 36},
    {name:"گلستان", code: 37},
    {name:"خراسان جنوبی", code: 38},
    {name:"خراسان شمالی", code: 39},
    {name:"البرز", code: 40}    
];

